((:name           "hmmer")
 (:repo           "https://github.com/HermitHan/hmmer")
 (:author         "KaiyuanHan")
 (:version        "3.4")
 (:dependencies)
 (:functions      "python3.12"
                  "alimask"
                  "hmmalign"
                  "hmmbuild"
                  "hmmconvert"
                  "hmmemit"
                  "hmmfetch"
                  "hmmlogo"
                  "hmmpgmd"
                  "hmmpgmd_shard"
                  "hmmpress"
                  "hmmscan"
                  "hmmsearch"
                  "hmmsim"
                  "hmmstat"
                  "jackhmmer"
                  "makehmmerdb"
                  "nhmmer"
                  "nhmmscan"
                  "phmmer"
                  "esl-afetch"
                  "esl-alimanip"
                  "esl-alimap"
                  "esl-alimask"
                  "esl-alimerge"
                  "esl-alipid"
                  "esl-alirev"
                  "esl-alistat"
                  "esl-compalign"
                  "esl-compstruct"
                  "esl-construct"
                  "esl-histplot"
                  "esl-mask"
                  "esl-mixdchlet"
                  "esl-reformat"
                  "esl-selectn"
                  "esl-seqrange"
                  "esl-seqstat"
                  "esl-sfetch"
                  "esl-shuffle"
                  "esl-ssdraw"
                  "esl-translate"
                  "esl-weight"))
